apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clouder-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clouder-deployment  # This must match the name of your Deployment
  minReplicas: 2  # Minimum number of pods
  maxReplicas: 5  # Maximum number of pods
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # Scale when CPU usage exceeds 50%
